### ISSUE TITLE
AttributeError: module 'recordlinkage' has no attribute 'Index'

### ISSUE THREAD

**Issue by boscoraju** [J535D165/recordlinkage#25]
Hi @J535D165,

I am trying to run the example provided but I am running into an error about no attribute "index".

index = recordlinkage.Index(df_a, df_b)
__________________________________________

  index = recordlinkage.Index(df_a, df_b)
AttributeError: module 'recordlinkage' has no attribute 'Index'

Any help is much appreciated. Thank you.

**Comment by J535D165** [comment]
Hello boscoraju,

I'm sorry for this stupid mistake. Use ``index = recordlinkage.Pairs(df_a, df_b)`` instead.

Index was used in an old version. 

For more docs: http://recordlinkage.readthedocs.io/en/latest/notebooks/link_two_dataframes.html

Good luck.

**Comment by froukehe9** [comment]
I've tried changing it to Pairs, but now have a problem with the index line from the example:

> 
politie_sample = politie_sel.sample(frac = 0.001)
lbz_sample = lbz_sel.sample(frac = 0.001)

indexer = recordlinkage.Pairs(politie_sample, lbz_sample)
indexer.block('Gender')
candidate_links = indexer.index(politie_sample, lbz_sample)

> Traceback (most recent call last):

  File "<ipython-input-134-5b9e19ea2dca>", line 6, in <module>
    candidate_links = indexer.index(politie_sample, lbz_sample)

  File "C:\Anaconda3\lib\site-packages\recordlinkage\indexing.py", line 330, in index
    d = next(self._iterindex(index_func, *args, **kwargs))

  File "C:\Anaconda3\lib\site-packages\recordlinkage\indexing.py", line 483, in _iterindex
    *args, **kwargs

TypeError: 'DataFrame' object is not callable

I've then tried to call the last line without data-frames as arguments, but then can't compute the length:

> Traceback (most recent call last):

  File "<ipython-input-136-1b6609c78ce4>", line 1, in <module>
    len(candidate_links)

TypeError: object of type 'method' has no len()

When I then try to use the Compare function (it asks for an argument, so I supplied the indexer object), I get the following error message:

> compare_cl = recordlinkage.Compare(indexer)
compare_cl.exact('Gender', 'Gender', label='Gender')
Traceback (most recent call last):

  File "<ipython-input-137-d0914696f1f7>", line 1, in <module>
    compare_cl = recordlinkage.Compare(indexer)

  File "C:\Anaconda3\lib\site-packages\recordlinkage\comparing.py", line 86, in __init__
    self.vectors = pandas.DataFrame(index=pairs)

  File "C:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 266, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)

  File "C:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 402, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)

  File "C:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 5411, in _arrays_to_mgr
    index = _ensure_index(index)

  File "C:\Anaconda3\lib\site-packages\pandas\indexes\base.py", line 3665, in _ensure_index
    return Index(index_like)

  File "C:\Anaconda3\lib\site-packages\pandas\indexes\base.py", line 312, in __new__
    subarr = _asarray_tuplesafe(data, dtype=object)

  File "C:\Anaconda3\lib\site-packages\pandas\core\common.py", line 369, in _asarray_tuplesafe
    values = list(values)

TypeError: 'Pairs' object is not iterable

Is there a way to go back to the original Index function?
