### ISSUE TITLE
Out of Memory Issue: Chunking?

### ISSUE THREAD

**Issue by spatialbits** [J535D165/recordlinkage#33]
Hey there. 

I'm having some trouble linking two large-ish CSVs (1M rows & 650k rows). I'm running into MemoryError exceptions when I execute the pair indexing. I'm using the chunksize parameter on the Pairs class but it doesn't seem to help. 
```Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/data/python/contact-match/match.py", line 122, in run_match
    pairs = pcl.block(left_on=left_cols, right_on=right_cols)
  File "/data/ve/ve-contact-match/lib/python3.4/site-packages/recordlinkage/indexing.py", line 478, in block
    on=on, left_on=left_on, right_on=right_on
  File "/data/ve/ve-contact-match/lib/python3.4/site-packages/recordlinkage/indexing.py", line 339, in index
    pairs = index_func(self.df_a, self.df_b, *args, **kwargs)
  File "/data/ve/ve-contact-match/lib/python3.4/site-packages/recordlinkage/indexing.py", line 44, in index_name_checker
    return func(df_a, df_b, *args, **kwargs)
  File "/data/ve/ve-contact-match/lib/python3.4/site-packages/recordlinkage/indexing.py", line 174, in _blockindex
    ).set_index([df_a.index.name, df_b.index.name])
  File "/data/ve/ve-contact-match/lib/python3.4/site-packages/pandas/core/frame.py", line 4607, in merge
    copy=copy, indicator=indicator)
  File "/data/ve/ve-contact-match/lib/python3.4/site-packages/pandas/tools/merge.py", line 62, in merge
    return op.get_result()
  File "/data/ve/ve-contact-match/lib/python3.4/site-packages/pandas/tools/merge.py", line 564, in get_result
    concat_axis=0, copy=self.copy)
  File "/data/ve/ve-contact-match/lib/python3.4/site-packages/pandas/core/internals.py", line 4825, in concatenate_block_managers
    placement=placement) for placement, join_units in concat_plan]
  File "/data/ve/ve-contact-match/lib/python3.4/site-packages/pandas/core/internals.py", line 4825, in <listcomp>
    placement=placement) for placement, join_units in concat_plan]
  File "/data/ve/ve-contact-match/lib/python3.4/site-packages/pandas/core/internals.py", line 4922, in concatenate_join_units
    for ju in join_units]
  File "/data/ve/ve-contact-match/lib/python3.4/site-packages/pandas/core/internals.py", line 4922, in <listcomp>
    for ju in join_units]
  File "/data/ve/ve-contact-match/lib/python3.4/site-packages/pandas/core/internals.py", line 5222, in get_reindexed_values
    fill_value=fill_value)
  File "/data/ve/ve-contact-match/lib/python3.4/site-packages/pandas/core/algorithms.py", line 1100, in take_nd
    out = np.empty(out_shape, dtype=dtype)
MemoryError
```
and my code:

```
pcl = rl.Pairs(df_left, df_right, chunks=1000)    # 

pairs = pcl.block(left_on='Last Name', right_on='Last Name')
```
I am still a tad newish with pandas so pls forgive me if I've missed something obvious.

**Comment by J535D165** [comment]
Thanks for the issue. This is a bit the result of a bad design of the Index class. I am working on an improvement, but it is time-consuming. 

There is a workaround. Will try to find some time tomorrow and post it here.

**Comment by spatialbits** [comment]
Great, thanks

**Comment by spatialbits** [comment]
So it seems if I override the blocking method and tell the merge to operate only on the left/right indices (_not_ column names) then it proceeds without running into a MemoryError.

```
    # Join
    pairs = data_left.reset_index().merge(
        data_right.reset_index(),
        how='inner',
        left_on=left_on,
        right_on=right_on,
    ).set_index([df_a.index.name, df_b.index.name])
```
Now becomes:
```
    # Join
    pairs = data_left.reset_index().merge(
        data_right.reset_index(),
        how='inner',
        left_index=True,
        right_index=True,
    ).set_index([df_a.index.name, df_b.index.name])
```

Have I missed something important here?

**Comment by J535D165** [comment]
How many unique last names do you have? Can you estimate how make record pairs you are expecting? The built-in [value_counts](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html) functions can be helpful. 

## making candidate record pairs with large files
```
file_a_generator = pandas.read_csv('file_a.csv', ..., chunksize=10000)
file_b_generator = pandas.read_csv('file_b.csv', ..., chunksize=10000)

matches = []

for df_a_chunk_i in file_a_generator:

    for df_b_chunk_i in file_b_generator:

        # make pairs
        pcl = rl.Pairs(df_a_chunk_i, df_b_chunk_i)   
        pairs = pcl.block(on='Last Name')
 
        # compare pairs 
        ...

        # classify pairs
        ...
        # append matches to list

```

- This works only in case of linking records between two files. Not for deduplication. 
- If you need to train a classifier, train it on a random subset of the data. Thereafter, use the predict method. 

I am trying to fix the chunk size bug. Also replacing the indexing class by another class.

**Comment by J535D165** [comment]
```
 # Join
    pairs = data_left.reset_index().merge(
        data_right.reset_index(),
        how='inner',
        left_index=True,
        right_index=True,
    ).set_index([df_a.index.name, df_b.index.name])
```

this is giving wrong results

**Comment by spatialbits** [comment]
Thanks! The work around for large files worked great.

**Comment by J535D165** [comment]
Great

Will keep this issue open until there is a solution for the deduplication case.

**Comment by amberjrivera** [comment]
Hi there, just checking to see if there are any updates for the deduplication case? I'm currently running into that error. My file for deduplication is about 560k records, and there are 28k unique values on the block column.

**Comment by Pav1777** [comment]
Hi 
I have used the above solution"making candidate record pairs with large files"
but I am getting an error:

Traceback (most recent call last):
  File "feature.py", line 98, in <module>
    block()
  File "feature.py", line 88, in block
    features = compare_cl.compute(pairs, df_a_chunk_i, df_b_chunk_i)
  File "/home/dhillon7/.local/lib/python2.7/site-packages/recordlinkage/base.py", line 849, in compute
    results = self._compute(pairs, x, x_link)
  File "/home/dhillon7/.local/lib/python2.7/site-packages/recordlinkage/base.py", line 712, in _compute
    result = feat._compute(data1, data2)
  File "/home/dhillon7/.local/lib/python2.7/site-packages/recordlinkage/base.py", line 454, in _compute
    result = self._compute_vectorized(*tuple(left_on + right_on))
  File "/home/dhillon7/.local/lib/python2.7/site-packages/recordlinkage/base.py", line 429, in _compute_vectorized
    raise NotImplementedError()
NotImplementedError

Any help is really  appreciated.

**Comment by Pav1777** [comment]
Hi
Just wanted to know how did you computed the feature vectors using chunk size when the size of two files is not same.  Because I am getting into error , because one of my file closes before the other when there is no more data to read from it. 

Pavneet
