### ISSUE TITLE
ImportError: cannot import name 'logsumexp'

### ISSUE THREAD

**Issue by connor924** [J535D165/recordlinkage#43]
Full error:
```
Traceback (most recent call last):

  File "<ipython-input-221-e68a19870618>", line 1, in <module>
    import recordlinkage

  File "/Users/connorhogendorn/anaconda/lib/python3.6/site-packages/recordlinkage/__init__.py", line 6, in <module>
    from recordlinkage.classifiers import *

  File "/Users/connorhogendorn/anaconda/lib/python3.6/site-packages/recordlinkage/classifiers.py", line 6, in <module>
    from sklearn import cluster, linear_model, naive_bayes, svm

  File "/Users/connorhogendorn/anaconda/lib/python3.6/site-packages/sklearn/cluster/__init__.py", line 6, in <module>
    from .spectral import spectral_clustering, SpectralClustering

  File "/Users/connorhogendorn/anaconda/lib/python3.6/site-packages/sklearn/cluster/spectral.py", line 17, in <module>
    from ..manifold import spectral_embedding

  File "/Users/connorhogendorn/anaconda/lib/python3.6/site-packages/sklearn/manifold/__init__.py", line 6, in <module>
    from .isomap import Isomap

  File "/Users/connorhogendorn/anaconda/lib/python3.6/site-packages/sklearn/manifold/isomap.py", line 11, in <module>
    from ..decomposition import KernelPCA

  File "/Users/connorhogendorn/anaconda/lib/python3.6/site-packages/sklearn/decomposition/__init__.py", line 19, in <module>
    from .online_lda import LatentDirichletAllocation

  File "/Users/connorhogendorn/anaconda/lib/python3.6/site-packages/sklearn/decomposition/online_lda.py", line 22, in <module>
    from ..utils.fixes import logsumexp

ImportError: cannot import name 'logsumexp'
```

I'm using sklearn version '0.18.1'

**Comment by J535D165** [comment]
Problem with dependency: https://stackoverflow.com/questions/43037903/importerror-cannot-import-name-logsumexp-when-importing-sklearn-model-selecti
