### ISSUE TITLE
Pickling Error over the server

### ISSUE THREAD

**Issue by Pav1777** [J535D165/recordlinkage#71]
Hi I am trying to compute feature vectors for days now by running my code over the server as it needs a lot of memory and computation . I have defined some custom comparing methods as well.  

```
 from recordlinkage.base import BaseCompareFeature
  def block():
        class comparemarriage(BaseCompareFeature):
        def _compute_vectorised(s1,s2):
                val1=s1
                val2=s2
                if (val1==6 and val2==1):
                    return(1)
               elif (val1==1 and (val2==4 or val2== 5)):
                    return(1)
               elif(val1==val2):
                    return(1)
               else:
                    return(0)
     df1=pd.read_csv('deduplicatedfinal71.csv',encoding='utf8',engine='python')
     df2=pd.read_csv('deduplicatednew81.csv',encoding='utf8',delimiter=',',engine='python')
      pcl = recordlinkage.index.Block(left_on=['PR_NAME_SURN','PR_NAME_GN'],
                                                         right_on=    ['SNAMLAST','SNAMFRST'])
     pairs= pcl.index(df1,df2)
     compare_cl = recordlinkage.Compare(n_jobs=16)

    compare_cl.string('PR_NAME_GN', 'SNAMFRST', method='jarowinkler',threshold=0.80,label='FirstJW')
    compare_cl.strin('PR_NAME_SURN', 'SNAMLAST',method='jarowinkler',threshold=0.80,label='LastJW')
    compare_cl.exact('SEX_CODE_STD','SEX',label='Gender')
    compare_cl.add(comparemarriage('MARITAL_STATUS','MARST',label='Marital-status'))

    features = compare_cl.compute(pairs, df1,df2)
    features=pd.DataFrame(features)
    features.to_csv('featurevector.csv',index=False)
```

I have only included some of the columns compared just to provide some idea what I am doing. On submitting it I get back the following error. I have been playing around this for a month now and this is my research project , I don't have enough time so need help badly.

```
Traceback (most recent call last):
  File "train.py", line 162, in <module>
    block()
  File "train.py", line 144, in block
    features = compare_cl.compute(pairs, df1,df2)
  File "/home/dhillon7/.local/lib/python2.7/site-packages/recordlinkage/base.py", line 852, in compute
    pairs, x, x_link, n_jobs=self.n_jobs)
  File "/home/dhillon7/.local/lib/python2.7/site-packages/recordlinkage/base.py", line 678, in _compute_parallel
    for chunk in df_chunks
  File "/home/dhillon7/.local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 996, in __call__
    self.retrieve()
  File "/home/dhillon7/.local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 899, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/dhillon7/.local/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 517, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/dhillon7/.local/lib/python2.7/site-packages/sklearn/externals/joblib/externals/loky/_base.py", line 426, in result
    return self.__get_result()
  File "/home/dhillon7/.local/lib/python2.7/site-packages/sklearn/externals/joblib/externals/loky/_base.py", line 381, in __get_result
    raise self._exception
**pickle.PicklingError: Could not pickle the task to send it to the workers.**
```

**Comment by J535D165** [comment]
Please try Python 3. Pickling is sometimes a bit hard with Python 2. 

The class `comparemarriage` is not vectorized. `_compute_vectorised` needs to return an `numpy.array` or `pandas.Series` of the size of `s1` and `s2`. (If I do understand you correctly)
